/** @type {[string, string, string, number][]} */
let kanjiList = [
    ['魚', 'さかな', 'Fish', 0x1],
    ['卵', 'たまご', 'Egg', 0x1],
    ['鞄', 'かばん', 'Bag', 0x1],
    ['時計', 'とけい', 'Watch', 0x1],
    ['大学', 'だいがく', 'University', 0x1],
    ['ああ', 'ああ', 'Ah!', 0x1],
    ['会う', 'あう', 'To Meet', 0x1],
    ['赤い', 'あかい', 'Red', 0x1],
    ['青い', 'あおい', 'Blue', 0x1],
    ['明るい', 'あかるい', 'Bright/Cheerful', 0x1],
    ['漢字', 'かんじ', 'Chinese Character', 0x1],
    ['お金', 'おかね', 'Money', 0x1],
    ['年', 'とし', 'Year', 0x1],
    ['月', 'つき', 'Moon', 0x1],
    ['男', 'おとこ', 'Male', 0x1],
    ['豚肉', 'ぶたにく', 'Pork', 0x1],
    ['部屋', 'へや', 'Room', 0x1],
    ['所', 'ところ', 'Place', 0x1],
    ['広い', 'ひろい', 'Spacious/Wide', 0x1],
    ['住む', 'すむ', 'To reside/live in', 0x1],
    ['協力', 'きょうりょく', 'Cooperation', 0x4],
    ['協約', 'きょうやく', 'Agreement/Contract', 0x4],
    ['棄却', 'ききゃく', 'Dismissal/Rejection', 0x4],
    ['冗談', 'じょうだん', 'Joke', 0x4],
    ['輝く', 'かがやく', 'Brighten', 0x4],
    ['瞳', 'ひとみ', 'Eye/Pupil', 0x4],
    ['食事', 'しょくじ', 'Meal', 0x2],
    ['定食', 'ていしょく', 'Meal Set/Course', 0x4],
    ['旨い', 'うまい', 'Delicious', 0x2],
    ['生きる', 'いきる', 'To Live/Exist', 0x2],
    ['生き', 'いき', 'Fresh', 0x4],
    ['広告', 'こうこく', 'Advertisement', 0x4],
    ['広報', 'こうほう', 'Publicity', 0x4],
    ['為', 'ため', 'for (something)', 0x2],
    ['基準', 'きじゅん', 'Standard', 0x4],
    ['場所', 'ばしょ', 'Place', 0x2],
    ['待避', 'たいひ', 'Shelter', 0x4],
    ['特典', 'とくてん', 'Privilege', 0x4],
    ['特に', 'とくに', 'Especially', 0x2],
    ['生る', 'なる', 'To Bear Fruit', 0x1],
    ['育む', 'はぐくむ', 'To Bring Up/Cultivate', 0x4],
    ['空気', 'くうき', 'Air/Atmosphere', 0x2],
    ['閉じる', 'とじる', 'To Close/Shut', 0x4],
    ['登る', 'のぼる', 'To Go Up', 0x1],
    ['奴', 'やつ', 'Fellow/Chap', 0x4],
    ['西', 'にし', 'West', 0x1],
    ['東', 'ひがし', 'East', 0x1],
    ['北', 'きた', 'North', 0x1],
    ['南', 'みなみ', 'South', 0x1],
    ['長い', 'ながい', 'Long', 0x1],
    ['怖い', 'こわい', 'Grim/Scary', 0x2],
    ['位', 'くらい', 'Rank', 0x4],
    ['布', 'ぬの', 'Cloth', 0x4],
    ['淀む', 'よどむ', 'To Stagnate', 0x4],
    ['国家', 'こっか', 'Nation/Country', 0x4],
    ['守る', 'まもる', 'To Guard', 0x4],
    ['戦い', 'たたかい', 'Battle/Combat', 0x4],
    ['驚愕', 'きょうがく', 'Amazement', 0x4],
    ['結末', 'けつまつ', 'Conclusion', 0x4],
    ['対峙', 'たいじ', 'Confrontation', 0x4],
    ['真似', 'まね', 'Imitation/Mimicry', 0x4],
    ['敵', 'てき', 'Opponent/Enemy', 0x4],
    ['万全', 'ばんぜん', 'Absolutely Sure', 0x4],
    ['多彩', 'たさい', 'Multicolored/Various', 0x4],
    ['民族', 'みんぞく', 'A Race/Nation', 0x4],
    ['視覚', 'しかく', 'The Sense of Sight', 0x4],
    ['不自由な', 'ふじゆうな', 'Inconvenient', 0x4],
    ['家族', 'かぞく', 'Family', 0x1],
    ['両面', 'りょうめん', 'Both Sides', 0x4],
    ['心理学', 'しんりがく', 'Psychology', 0x4],
    ['子供', 'こども', 'Child', 0x1],
    ['上手', 'じょうず', 'Skilled', 0x1],
    ['喜ばす', 'よろこばす', 'To Please/Satisfy', 0x4],
    ['草花', 'くさばな', 'A Flowering Plant', 0x4],
    ['富士山', 'ふじさん', 'Mount Fuji', 0x4],
    ['他人', 'たにん', 'Unrelated Person', 0x4],
    ['無言', 'むごん', 'Silent', 0x4],
    ['不快な', 'ふかいな', 'Displeasing', 0x4],
    ['天気', 'てんき', 'Weather', 0x1],
    ['物語', 'ものがたり', 'Story/Narrative', 0x4],
    ['音楽', 'おんがく', 'Music', 0x1],
    ['筆記', 'ひっき', 'Note-Taking', 0x4],
    ['習慣', 'しゅうかん', 'A Habit', 0x2],
    ['刊行', 'かんこう', 'A Publication', 0x4],
    ['消失する', 'しょうしつする', 'To Disappear/Vanish', 0x4],
    ['神秘', 'しんぴ', 'Mysterious', 0x4],
    ['変人', 'へんじん', 'An Eccentric', 0x4],
    ['君', 'きみ', 'You', 0x2],
    ['借りる', 'かりる', 'To Borrow', 0x1],
    ['天空', 'てんくう', 'Sky/Air', 0x4],
    ['等', 'など', '"...and so on"', 0x1],
    ['限り', 'かぎり', 'Limit', 0x4],
    ['現在', 'げんざい', 'The Present', 0x4],
    ['始まる', 'はじまる', 'To Begin', 0x1],
    ['日付け', 'ひづけ', 'Dating/A Date', 0x4],
    ['企業', 'きぎょう', 'An Endeavor/Company', 0x4],
    ['企む', 'たくらむ', 'To Plot', 0x4],
    ['企て', 'くわだて', 'An Attempt', 0x4],
    ['様々', 'さまざま', 'Various', 0x4],
    ['役に立つ', 'やくにたつ', 'To Help/Serve', 0x2],
    ['独自', 'どくじ', 'Original', 0x4],
    ['独り', 'ひとり', 'Alone/Unmarried', 0x4],
    ['親友', 'しんゆう', 'Best Friend', 0x4],
    ['親', 'おや', 'Parents', 0x2],
    ['方法', 'ほうほう', 'Method/Technique', 0x4],
    ['暖める', 'あたためる', 'To Warm', 0x4],
    ['亜鉛', 'あえん', 'Zinc', 0x4],
    ['家庭', 'かてい', 'A Household/Family', 0x1],
    ['世紀', 'せいき', 'Century', 0x4],
    ['冬', 'ふゆ', 'Winter', 0x1],
    ['夜', 'よる', 'Night', 0x1],
    ['最初', 'さいしょ', 'First', 0x2],
    ['最適', 'さいてき', 'Best', 0x4],
    ['山登り', 'やまのぼり', 'Mountain Climbing', 0x4],
    ['地下鉄', 'ちかてつ', 'Subway Train', 0x1],
    ['自転車', 'じてんしゃ', 'Bicycle', 0x1],
    ['駐車場', 'ちゅうしゃじょう', 'Parking Lot', 0x2],
    ['触る', 'さわる', 'To Touch', 0x2],
    ['座る', 'すわる', 'To Sit', 0x1],
    ['危ない', 'あぶない', 'Dangerous', 0x1],
    ['生じる', 'しょうじる', 'To Bear/Germinate', 0x4],
    ['締切り', 'しめきり', 'Deadline', 0x4],
    ['呼ぶ', 'よぶ', 'To Call/Summon', 0x1],
    ['帯', 'おび', 'Obi (Belt)', 0x4],
    ['確か', 'たしか', 'Certainly/Probably', 0x2],
    ['罪', 'つみ', 'Sin', 0x4],
    ['泣ける', 'なける', 'To Feel Like Crying', 0x4],
    ['投げる', 'なげる', 'To Throw', 0x2],
    ['詳しい', 'くわしい', 'Particular/Detailed', 0x4],
    ['耕す', 'たがやす', 'To Plow/Tend Land', 0x4],
    ['眠る', 'ねむる', 'To Sleep', 0x2],
    ['音量', 'おんりょう', 'Volume (of Sound)', 0x4],
    ['競輪', 'けいりん', 'Bicycle Race', 0x4],
    ['妨げ', 'さまたげ', 'Obstruction', 0x4],
    ['過失', 'かしつ', 'An Error/Mistake', 0x4],
    ['損傷', 'そんしょう', 'Damage', 0x4],
    ['角', 'かど', 'A Corner/Edge', 0x1],
    ['門', 'もん', 'Gate', 0x1],
    ['動植物', 'どうしょくぶつ', 'Flora and Fauna', 0x4],
    ['惑星', 'わくせい', 'Planet', 0x4],
    ['動き', 'うごき', 'A Movement', 0x2],
    ['突然', 'とつぜん', 'Sudden', 0x4],
    ['起こす', 'おこす', 'To Wake Up/Raise', 0x2],
    ['見本', 'みほん', 'A Sample', 0x4],
    ['辞書', 'じしょ', 'Dictionary', 0x1],
    ['結婚', 'けっこん', 'Marriage', 0x1],
    ['両家', 'りょうけ', 'Both Families', 0x4],
    ['争い', 'あらそい', 'Competition/Rivalry', 0x4],
    ['才能', 'さいのう', 'An Ability/Talent', 0x4],
    ['約', 'やく', 'Approximately/About', 0x4],
    ['国際', 'こくさい', 'International', 0x4],
    ['妨げる', 'さまたげる', 'To Obstruct/Prevent', 0x4],
    ['操業', 'そうぎょう', 'Operation', 0x4],
    ['時間', 'じかん', 'Time', 0x1],
    ['水', 'みず', 'Water', 0x1],
    ['三日', 'みっか', 'Third Day/Three Days', 0x1],
    ['野菜', 'やさい', 'Vegetable', 0x1],
    ['夕方', 'ゆうがた', 'Evening', 0x1],
    ['八日', 'ようか', 'Eight Days/Eighth Day', 0x1],
    ['四日', 'よっか', 'Four Days/Fourth Day', 0x1],
    ['弱い', 'よわい', 'Weak/Feeble', 0x1],
    ['友達', 'ともだち', 'Friend', 0x1],
    ['鶏肉', 'とりにく', 'Chicken Meat', 0x1],
    ['寝る', 'ねる', 'To Sleep', 0x1],
    ['脱ぐ', 'ぬぐ', 'To Take Clothes Off', 0x1],
    ['外', 'ほか', 'Other/Remaining Place(s)', 0x1],
    ['意見', 'いけん', 'Viewpoint/Opinion', 0x2],
    ['医学', 'いがく', 'Medicine (Studies)', 0x2],
    ['いじめる', 'いじめる', 'To Tease', 0x2],
    ['校長', 'こうちょう', 'Headmaster', 0x2],
    ['様', 'さま', 'Mr. or Mrs. (honorific)', 0x2],
    ['柔道', 'じゅうどう', 'Judo', 0x2],
    ['説明', 'せつめい', 'Explanation', 0x2],
    ['台風', 'たいふう', 'Typhoon', 0x2],
    ['今', 'いま', 'Now', 0x1],
    ['五日', 'いつか', 'Five Days/Fifth Day', 0x1],
    ['英語', 'えいご', 'The English Language', 0x1],
    ['うるさい', 'うるさい', 'Loud/Annoying', 0x1],
    ['絵', 'え', 'Picture/Painting', 0x1],
    ['お酒', 'おさけ', 'Sake/Alcohol', 0x1],
    ['皿', 'さら', 'Plate/Platter', 0x1],
    ['面白い', 'おもしろい', 'Amusing/Interesting', 0x1],
    ['回', 'かい', 'Times/Occurence (counter)', 0x0],
    ['声', 'こえ', 'Voice', 0x1],
    ['丈夫', 'じょうぶ', 'Strong/Durable', 0x1],
    ['吸う', 'すう', 'To Smoke/Breathe in', 0x1],
    ['少し', 'すこし', 'A Little', 0x1],
    ['出口', 'でぐち', 'Exit', 0x0],
    ['入り口', 'いりぐち', 'Entrance', 0x1],
    ['会議', 'かいぎ', 'Conference/Meeting', 0x2],
    ['後ろ', 'うしろ', 'Behind/Rear', 0x1],
    ['薄い', 'うすい', 'Thin/Weak', 0x1],
    ['今日', 'きょう', 'Today', 0x1],
    ['高い', 'たかい', 'Tall/Expensive', 0x1],
    ['下りる', 'おりる', 'To descend', 0x2],
    ['着物', 'きもの', 'Kimono', 0x2],
    ['交通', 'こうつう', 'Traffic', 0x2],
    ['工業', 'こうぎょう', 'Industry', 0x2],
    ['随分', 'ずいぶん', 'Extremely', 0x2],
    ['再生', 'さいせい', 'Playback', 0x4],
    ['動画', 'どうが', 'Video', 0x4],
    ['症状', 'しょうじょう', 'Symptoms/Condition', 0x4],
    ['接続', 'せつぞく', 'Connection', 0x4],
    ['線', 'せん', 'Line/Thread', 0x2],
    ['来る', 'くる', 'To come/arrive', 0x4],
    ['狂う', 'くるう', 'To go mad/get out of order', 0x4],
    ['計算', 'けいさん', 'Calculation/Reckoning', 0x4],
    ['警察', 'けいさつ', 'Police', 0x4],
    ['蛍光灯', 'けいこうとう', 'Fluorescent lamp', 0x4],
    ['重体', 'じゅうたい', 'Seriously Ill', 0x4],
    ['終点', 'しゅうてん', 'Terminus/Last Stop', 0x4],
    ['集中', 'しゅうちゅう', 'Concentrating/Focusing', 0x4],
    ['収入', 'しゅうにゅう', 'Income/Revenue', 0x4],
    ['先祖', 'せんぞ', 'Ancestor', 0x4],
    ['戦争', 'せんそう', 'War', 0x4],
    ['専門', 'せんもん', 'Specialty/Expertise', 0x4],
    ['像', 'ぞう', 'Elephant', 0x4],
    ['相互', 'そうご', 'Mutual/Reciprocal', 0x4],
    ['手入れ', 'ていれ', 'Repairs/Maintenance', 0x4],
    ['七夕', 'たなばた', 'Festival of the Seventh/Qi Xi', 0x4],
    ['好き', 'すき', 'Fondness/Liking', 0x1],
    ['易しい', 'やさしい', 'Plain/Simple', 0x2],
    ['悲しい', 'かなしい', 'Sad', 0x2],
    ['人口', 'じんこう', 'Population', 0x4],
    ['奇麗', 'きれい', 'Beautiful', 0x4],
    ['首都', 'しゅと', 'Capital City', 0x4],
    ['稲妻', 'いなずま', 'Lightning', 0x4],
    ['寒い', 'さむい', 'Cold', 0x1],
    ['暗い', 'くらい', 'Dark/Gloomy', 0x4],
    ['薄暗い', 'うすぐらい', 'Dim/Gloomy', 0x4],
    ['桜', 'さくら', 'Cherry Blossom', 0x1],
    ['必要', 'ひつよう', 'Necessary', 0x4],
    ['不味い', 'まずい', 'Terrible/Horrible (food or drink)', 0x4],
    ['失礼', 'しつれい', 'Rude', 0x4],
    ['適当', 'てきとう', 'Appropriate/Suitable', 0x4],
    ['駄目', 'だめ', 'No Good/Forbidden', 0x4],
    ['上着', 'うわぎ', 'Outerwear', 0x1],
    ['狭い', 'せまい', 'Narrow', 0x1],
    ['大変', 'たいへん', 'Serious/Hard', 0x4],
    ['冗長な', 'じょうちょうな', 'Redundant', 0x4],
    ['冗費', 'じょうひ', 'Unnecessary Expenses', 0x4],
    ['冗漫な', 'じょうまんな', 'Verbose', 0x4],
    ['剰余', 'じょうよ', 'Remainder', 0x4],
    ['城', 'しろ', 'Castle', 0x4],
    ['廊下', 'ろうか', 'Corridor', 0x1],
    ['練習', 'れんしゅう', 'Practice', 0x1],
    ['若い', 'わかい', 'Young', 0x1],
    ['私', 'わたし', 'I/Me', 0x1],
    ['冷蔵庫', 'れいぞうこ', 'Refrigerator', 0x1],
    ['戦', 'いくさ', 'War/Battle', 0x4],
    ['鉢巻き', 'はちまき', 'Headband', 0x4],
    ['開始', 'かいし', 'Opening/Starting Point', 0x4],
    ['手袋', 'てぶくろ', 'Glove', 0x2],
    ['素晴らしい', 'すばらしい', 'Wonderful', 0x2],
    ['砂', 'すな', 'Sand', 0x2],
    ['素早い', 'すばやい', 'Quick/Prompt', 0x4],
    ['摩損', 'まそん', 'Attrition/Abrasiveness', 0x4],
    ['丸窓', 'まるまど', 'Circular Window/Porthole', 0x4],
    ['宝', 'たから', 'Treasure', 0x4],
    ['人生', 'じんせい', 'Life', 0x4],
    ['生活', 'せいかつ', 'Lifestyle', 0x2],
    ['水田', 'すいでん', 'Rice Field', 0x4],
    ['油田', 'ゆでん', 'Oil Field', 0x4],
    ['白人', 'はくじん', 'Caucasian', 0x4],
    ['白米', 'はくまい', 'Polished Rice', 0x4],
    ['注目', 'ちゅうもく', 'Attention', 0x4],
    ['目的', 'もくてき', 'Goal', 0x4],
    ['石油', 'せきゆ', 'Petroleum', 0x4],
    ['宝石', 'ほうせき', 'Gemstone', 0x4],
    ['耳障り', 'みみざわり', 'Offensive', 0x4],
    ['耳鼻科', 'じびか', 'Ear/Nose Doctor', 0x4],
    ['生け花', 'いけばな', 'Flower Arrangement', 0x4],
    ['花火', 'はなび', 'Fireworks', 0x4],
    ['赤字', 'あかじ', 'Debt ("the red")', 0x4],
    ['赤十字', 'せきじゅうじ', 'The Red Cross', 0x4],
    ['手足', 'てあし', 'Hand and Foot', 0x4],
    ['補足', 'ほそく', 'Supplement', 0x4],
    ['金持ち', 'かねもち', 'Rich Person', 0x2],
    ['金属', 'きんぞく', 'Metal', 0x4],
    ['今年', 'ことし', 'This Year', 0x1],
    ['来年', 'らいねん', 'Next Year', 0x1],
    ['少女', 'しょうじょ', 'Little Girl', 0x4],
    ['少年', 'しょうねん', 'Little Boy', 0x4],
    ['南沙諸島', 'なんさしょとう', 'The Spratly Islands', 0x4],
    ['千', 'せん', 'Thousand', 0x1],
    ['万', 'まん', 'Ten Thousand', 0x1],
    ['千万', 'せんまん', 'Ten Million', 0x1],
    ['円', 'えん', 'Yen/Round', 0x1],
    ['半分', 'はんぶん', 'Half (Portion)', 0x1],
    ['半島', 'はんとう', 'Peninsula', 0x4],
    ['提出', 'ていしゅつ', 'Submission', 0x4],
    ['夏', 'なつ', 'Summer', 0x1],
    ['夏休み', 'なつやすみ', 'Summer Vacation', 0x1],
    ['初夏', 'しょか', 'Early Summer', 0x4],
    ['真夏', 'まなつ', 'Midsummer', 0x4],
    ['百人', 'ひゃくにん', 'Hundred People', 0x4],
    ['百万', 'ひゃくまん', 'One Million', 0x1],
    ['天才', 'てんさい', 'Genius', 0x4],
    ['雨天', 'うてん', 'Rainy Weather', 0x4],
    ['青空', 'あおぞら', 'Blue Sky', 0x4],
    ['青年', 'せいねん', 'Youth/Young Man', 0x4],
    ['緑', 'みどり', 'Green', 0x1],
    ['大雨', 'おおあめ', 'Heavy Rain', 0x1],
    ['雨量', 'うりょう', 'Rainfall', 0x4],
    ['休日', 'きゅうじつ', 'Holiday', 0x4],
    ['定休', 'ていきゅう', 'Fixed Holiday', 0x4],
    ['会社', 'かいしゃ', 'Company', 0x1],
    ['社会', 'しゃかい', 'Society', 0x2],
    ['合計', 'ごうけい', 'Total/Sum', 0x4],
    ['合同', 'ごうどう', 'Combination', 0x4],
    ['作品', 'さくひん', 'A Work/Creation', 0x4],
    ['作文', 'さくぶん', 'Composition/Writing', 0x1],
    ['今晩', 'こんばん', 'Tonight', 0x1],
    ['深夜', 'しんや', 'Midnight', 0x4],
    ['昼夜', 'ちゅうや', 'Day and Night', 0x4],
    ['東京', 'とうきょう', 'Tokyo', 0x1],
    ['京都', 'きょうと', 'Kyoto', 0x1],
    ['元気', 'げんき', 'Health/Energy', 0x1],
    ['元始', 'げんし', 'Origin', 0x4],
    ['東西', 'とうざい', 'East and West', 0x4],
    ['東日本', 'ひがしにほん', 'East Japan', 0x1],
    ['未来', 'みらい', 'Future', 0x4],
    ['来月', 'らいげつ', 'Next Month', 0x1],
    ['思い出す', 'おもいだす', 'To Remember', 0x2],
    ['南北', 'なんぼく', 'North and South', 0x4],
    ['南米', 'なんべい', 'South America', 0x4],
    ['古文', 'こぶん', 'Ancient Writing', 0x4],
    ['古代', 'こだい', 'Ancient Times', 0x4],
    ['古い', 'ふるい', 'Old', 0x1],
    ['北米', 'ほくべい', 'North America', 0x4],
    ['北風', 'きたかぜ', 'Northerly Winds', 0x4],
    ['力', 'ちから', 'Power', 0x2],
    ['力士', 'りきし', 'Sumo Wrestler', 0x4],
    ['力持ち', 'ちからもち', 'Strong Person', 0x4],
    ['切手', 'きって', 'Postage Stamp', 0x1],
    ['切符', 'きっぷ', 'Ticket', 0x1],
    ['切る', 'きる', 'To cut', 0x1],
    ['五円', 'ごえん', 'Five Yen', 0x1],
    ['円高', 'えんだか', 'High-valued Yen', 0x4],
    ['前日', 'ぜんじつ', 'The Day Before', 0x4],
    ['名前', 'なまえ', 'Name', 0x1],
    ['入学', 'にゅうがく', 'Entering School/Matriculation', 0x2],
    ['入る', 'はいる', 'To Enter/Contain', 0x1],
    ['何人', 'なんにん', 'How Many People?', 0x1],
    ['何日', 'なんにち', 'How Many Days?', 0x1],
    ['似る', 'にる', 'To Be Similar', 0x2],
    ['人形', 'にんぎょう', 'Doll/Puppet', 0x2],
    ['日記', 'にっき', 'Diary/Journal', 0x2],
    ['盗む', 'ぬすむ', 'To Steal', 0x2],
    ['慣れる', 'なれる', 'To Grow Accustomed', 0x2],
    ['鳴る', 'なる', 'To Ring/Resound', 0x2],
    ['値段', 'ねだん', 'Price', 0x2],
    ['歯', 'は', 'Tooth', 0x2],
    ['熱', 'ねつ', 'Fever', 0x2],
    ['逃げる', 'にげる', 'To Escape', 0x2],
    ['苦い', 'にがい', 'Bitter', 0x2],
    ['寝坊', 'ねぼう', 'Oversleeping', 0x2],
    ['眠い', 'ねむい', 'Sleepy', 0x2],
    ['眠る', 'ねむる', 'To Sleep', 0x2],
    ['残る', 'のこる', 'To Remain/Be Left', 0x2],
    ['葉', 'は', 'Leaf', 0x2],
    ['場合', 'ばあい', 'Case/Situation', 0x2],
    ['乗り物', 'のりもの', 'Vehicle', 0x2],
    ['乗り換える', 'のりかえる', 'To Transfer(eg. a train)', 0x2],
    ['倍', 'ばい', 'Twice/Double', 0x2],
    ['拝見', 'はいけん', 'Examining/Looking At', 0x2],
    ['歯医者', 'はいしゃ', 'Dentist', 0x2],
    ['運ぶ', 'はこぶ', 'To Transport/Carry', 0x2],
    ['恥ずかしい', 'はずかしい', 'Shy/Embarrassed', 0x2],
    ['発音', 'はつおん', 'Pronunciation', 0x2],
    ['花見', 'はなみ', 'Cherry Blossom Viewing', 0x2],
    ['林', 'はやし', 'Woods', 0x2],
    ['反対', 'はんたい', 'Opposition/Resistance', 0x2],
    ['払う', 'はらう', 'To Pay', 0x2],
    ['番組', 'ばんぐみ', 'Program (e.g. TV)', 0x2],
    ['日', 'ひ', 'Sun', 0x2],
    ['火', 'ひ', 'Fire', 0x2],
    ['冷える', 'ひえる', 'To Become Cold', 0x2],
    ['光る', 'ひかる', 'To Shine', 0x2]
];
